---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: telegraf_pre.yml
- include_tasks: telegraf_install.yml

- block: # Config Telegraf
  - include_tasks: telegraf_search_config.yml
  - include_tasks: telegraf_post.yml
  tags:
    - telegraf-config
    - telegraf-drop-config
